### ISSUE TITLE
关于api的接口

### ISSUE THREAD

**Issue by JauYang** [ecitlm/Vue-news#1]
ecitlm你好，我最近也想学习Vuejs，能否将您code中的api接口整理出来呢？这样更方便大家去学习了，先行感谢！

**Comment by ecitlm** [comment]
接口在项目里面的API文件夹

**Comment by cage0315** [comment]
ecitlm大神  你好   可以发下联系方式聊聊吗？项目中有些东西不太懂可以请教请教吗？

**Comment by ecitlm** [comment]
@cage0315 Q 2531495134

**Comment by ecitlm** [comment]
@JauYang  接口数据已经整理一个项目  基于Thinkphp   只有用php环境部署无需链接数据库，接口直接使用相关接口 https://github.com/ecitlm/TP5_Splider
